WebAppMVC/Controllers/AtletasController.cs
using ApiCatalogo.Repository;
using DATA.Contexts;
using DOMAIN.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebAppMVC.Controllers
{
    public class AtletasController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IUnitOfWork uof;

        public AtletasController(AppDbContext context, IUnitOfWork uof)
        {
            this._context = context;
            this.uof = uof;
        }

        public async Task<IActionResult> Index()
        {
            var atletas = await this.uof.AtletaRepository.GetAllAsyn();
            return View(atletas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Atleta atleta)
        {
            if (ModelState.IsValid)
            {
                var newEq = this.uof.AtletaRepository.Add(atleta);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

WebAppMVC/Controllers/JogosController.cs
using ApiCatalogo.Repository;
using DATA.Contexts;
using DOMAIN.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebAppMVC.Controllers
{
    public class JogosController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IUnitOfWork uof;

        public JogosController(AppDbContext context, IUnitOfWork uof)
        {
            this._context = context;
            this.uof = uof;
        }

        public async Task<IActionResult> Index()
        {
            var jogos = await this.uof.JogoRepository.GetAllAsyn();
            return View(jogos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Jogo jogo)
        {
            if (ModelState.IsValid)
            {
                var newEq = this.uof.JogoRepository.Add(jogo);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

WebAppMVC/Controllers/OrdensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiCatalogo.Repository;
using DATA.Contexts;
using DOMAIN.Interfaces.Repositories;
using DOMAIN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebAppMVC.ViewModels;

namespace WebAppMVC.Controllers
{
    public class OrdensController : Controller
    {
        private readonly IUnitOfWork uof;
        private readonly OrdemVM ordemVM;
        private readonly ILogger<HomeController> _logger;


        public OrdensController(ILogger<HomeController> logger, IUnitOfWork uof)
        {
            this._logger = logger;
            this.uof = uof;
            this.ordemVM = new OrdemVM(uof);
        }

        // GET: Ordens
        public async Task<IActionResult> Index(string tipoOrdem)
        {
            ViewBag.TipoOrdem = new SelectList(this.uof.TipoOrdemRepository.GetAll(), "Id", "Nome");
            var ordens = this.uof.OrdemRepository.GetAllIncluding(ordem => ordem.TipoOrdem);

            var id = Convert.ToInt32(tipoOrdem);
            if (id > 0)
            {
                var ordensFiltered = ordens.Where(ord => ord.TipoOrdem.Id.Equals(id));
                this._logger.LogInformation($"Usuário acessou a página de Ordens. Filtrou pelo tipo {ordensFiltered.FirstOrDefault()?.TipoOrdem.Nome}");
                this._logger.LogInformation($"Foram encontrados {ordensFiltered.Count()} ordens");
                return View(ordensFiltered);
            }
            else
            {
                this._logger.LogInformation($"Usuário acessou a página de Ordens. Não filtrou por nenhum tipo");
                this._logger.LogInformation($"Foram encontrados {ordens.Count()} ordens");
                return View(ordens);
            }
        }

        // GET: Ordens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var ordem = this.uof.OrdemRepository.GetAllIncluding(ordem => ordem.TipoOrdem)
                .FirstOrDefault(ord => ord.Id.Equals(id));

            if (ordem == null)
                return NotFound();

            ViewBag.TipoOrdem = new SelectList(this.uof.TipoOrdemRepository.GetAll(), "Id", "Nome", ordem.TipoOrdem.Id);

            return View(ordem);
        }

        // GET: Ordens/Create
        public IActionResult Create()
        {
            ViewBag.TipoOrdem = new SelectList(this.uof.TipoOrdemRepository.GetAll(), "Id", "Nome");
            return View();
        }

        public IActionResult CreateByVM()
        {
            return View(this.ordemVM);
        }

        // POST: Ordens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Id")] Ordem ordem, string tipoOrdem)
        {
            var tipoOrdemId = Convert.ToInt32(tipoOrdem);
            if (tipoOrdemId <= 0)
            {
                ViewBag.TipoOrdem = new SelectList(this.uof.TipoOrdemRepository.GetAll(), "Id", "Nome");
                return View();
            }

            ordem.TipoOrdem = this.uof.TipoOrdemRepository.GetAll().FirstOrDefault(to => to.Id.Equals(tipoOrdemId));
            if (ModelState.IsValid)
            {
                this.uof.OrdemRepository.Add(ordem);
                return RedirectToAction(nameof(Index));
            }

            return View(ordem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateByVM(Ordem ordem, string tipoOrdem)
        {
            var tipoOrdemId = Convert.ToInt32(tipoOrdem);
            if (tipoOrdemId <= 0)
                return View(this.ordemVM);

            ordem.TipoOrdem = this.uof.TipoOrdemRepository.GetAll().FirstOrDefault(to => to.Id.Equals(tipoOrdemId));
            if (ModelState.IsValid)
            {
                this.uof.OrdemRepository.Add(ordem);
                return RedirectToAction(nameof(Index));
            }

            return View(this.ordemVM);
        }

        // GET: Ordens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var ordem = this.uof.OrdemRepository.GetAllIncluding(ordem => ordem.TipoOrdem)
                .FirstOrDefault(ord => ord.Id.Equals(id));
            if (ordem == null)
                return NotFound();

            ViewBag.TipoOrdem = new SelectList(this.uof.TipoOrdemRepository.GetAll(), "Id", "Nome", ordem.TipoOrdem.Id);

            return View(ordem);
        }

        // POST: Ordens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,Id")] Ordem ordem)
        {
            if (id != ordem.Id)
                return NotFound();

            var tipoOrdemId = Convert.ToInt32(Request.Form["TipoOrdem"]);
            ordem.TipoOrdem = this.uof.TipoOrdemRepository.GetAll().FirstOrDefault(to => to.Id.Equals(tipoOrdemId));

            if (ModelState.IsValid)
            {
                try
                {
                    await this.uof.OrdemRepository.UpdateAsyn(ordem, ordem.Id);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdemExists(ordem.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(ordem);
        }

        // GET: Ordens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var ordem = await this.uof.OrdemRepository.GetAsync((int) id);
            if (ordem == null)
                return NotFound();

            return View(ordem);
        }

        // POST: Ordens/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordem = await this.uof.OrdemRepository.GetAsync(id);
            this.uof.OrdemRepository.Delete(ordem);
            return RedirectToAction(nameof(Index));
        }

        private bool OrdemExists(int id)
        {
            return this.uof.OrdemRepository.GetAsync(id) != null;
        }
    }
}

WebAppMVC/Controllers/ScoutsController.cs
using ApiCatalogo.Repository;
using DATA.Contexts;
using DOMAIN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppMVC.ViewModels;

namespace WebAppMVC.Controllers
{
    public class ScoutsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IUnitOfWork uof;
        private List<ScoutGeral> scouts;
        private List<RankingScoutVM> ranking;

        public ScoutsController(AppDbContext context, IUnitOfWork uof)
        {
            this._context = context;
            this.uof = uof;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            scouts = GetAllScouts();
            return View(scouts);
        }

        public IActionResult Create()
        {
            ViewBag.Atletas = new SelectList(this._context.Atletas.OrderBy(it => it.Nome).ToList(), "Id", "Nome");
            ViewBag.Jogos = new SelectList(this._context.Jogos.OrderBy(it => it.Numero).ToList(), "Id", "Nome");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Ranking()
        {
            this.ranking = GetRanking();            
            var relatorio = new RelatorioScoutVM(this.ranking);
            return View(relatorio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ScoutGeral scout, string atletas, string dropDownJogo)
        {
            var idAtleta = Convert.ToInt32(atletas);
            var idJogo = Convert.ToInt32(dropDownJogo);
            if(idAtleta <= 0 || idJogo <= 0)
            {
                ViewBag.Atletas = new SelectList(this._context.Atletas, "Id", "Nome");
                ViewBag.Jogos = new SelectList(this._context.Jogos, "Id", "Nome");
                return View();
            }


            if (ModelState.IsValid)
            {
                scout.idAtleta = idAtleta;
                scout.idJogo = idJogo;
                var newEq = this.uof.ScoutGeralRepository.Add(scout);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpPost]
        public JsonResult GetJogosByAtletaId(int idAtleta)
        {
            var todosJogos = _context.Jogos;
            var ids = (from jogo in todosJogos
                        join scout in _context.ScoutsGerais on jogo.Id equals scout.idJogo
                        where scout.idAtleta == idAtleta
                        select jogo.Id).ToList();


            return Json(new {data= todosJogos.Where(it => !ids.ToList().Contains(it.Id)) });
        }

        private List<ScoutGeral> GetAllScouts()
        {
            return uof.ScoutGeralRepository.GetAllIncluding(scouts => scouts.atleta, scouts => scouts.jogo).OrderBy(s => s.jogo.Numero).ThenBy(s => s.atleta.Nome).ToList(); ;
        }

        private List<RankingScoutVM> GetRanking()
        {
            this.scouts = GetAllScouts();
            return (from sc in scouts
                           group sc by sc.atleta.Nome into g
                           select new RankingScoutVM
                           {
                               Atleta = g.First().atleta,
                               nGols = g.Sum(pc => pc.gol),
                               nAssistencias = g.Sum(pc => pc.assistencia),
                               nAmarelos = g.Sum(pc => pc.cartaAmarelo),
                               nVermelhos = g.Sum(pc => pc.cartaVermelho),
                           }).ToList();
        }
    }
}

WebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B3 Analytics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
        }

            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 14px 16px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }

            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: darkblue;
            }

        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .mynav_dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .mynav_dropdown-content a:hover {
                    background-color: #ddd;
                }

        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }

        .icon {
            padding: 10px;
            background: dodgerblue;
            color: white;
            min-width: 50px;
            text-align: center;
        }

        .teste {
            display: inline-block;
            width: 1000px;
            height: 80px;
        }

        .teste2 {
            width: 100%;
            height: 50px;
        }

        .txt-branco {
            font-family: Arial, Geneva, Tahoma, sans-serif;
            color: black;
        }

        .testeDiv {
            width: 100px;
            height: 50px;
            display: table;
            margin: 30px auto;
            text-align: center;
            border-radius: 8px;
        }

        .box {
            width: 100%;
            height: 50px;
            display: inline-block;
            margin: 30px auto;
            text-align: center;
            /*background-color: #1b6ec2;*/
            background-color: lightblue;
            border-radius: 8px;
            box-shadow: 4px 4px 12px rgba(0, 0, 0, 0.15);
        }

        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba( 255, 255, 255, .8 ) url('https://i.imgur.com/kv2oHwT.gif') 50% 50% no-repeat;
            /*background: rgba( 255, 255, 255, .8 ) url('https://i.pinimg.com/originals/d5/76/eb/d576eb5196c292219de847dd8b1b25fc.gif') 50% 50% no-repeat;*/
        }
      /*  .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba( 255, 255, 255, .8 ) url('http://i.stack.imgur.com/FhHRx.gif') 50% 50% no-repeat;
        }*/

        /* When the body has the loading class, we turn
        the scrollbar off with overflow:hidden */
        body.loading {
            overflow: hidden;
        }

        /* Anytime the body has the loading class, our
        modal element will be visible */
        body.loading .modal {
            display: block;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <div class="mynav_navbar">
                    <a asp-area="" asp-controller="Home" asp-action="Index">RLF</a>
                    <div class="mynav_dropdown">
                        <button class="mynav_dropbtn">
                            B3
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="mynav_dropdown-content">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="HistoricalStockPrices" asp-action="Index">Cotações</a>*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnaliseLucro" asp-action="Index">Análise por Ativo</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnaliseLucro" asp-action="LucroResumido">Análise por Ativo Resumido</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnaliseLucro" asp-action="ConsolidacaoAtivos">Consolidação Ativos</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnaliseLucro" asp-action="ConsolidacaoAtivosTeste">Consolidação Ativos Teste</a>
                        </div>
                    </div>
                    @*<div class="mynav_dropdown">
                            <button class="mynav_dropbtn">
                                Ordem
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mynav_dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ordens" asp-action="Index">Ordens</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TipoOrdem" asp-action="Index">Tipos de Ordem</a>
                            </div>
                        </div>
                        <div class="mynav_dropdown">
                            <button class="mynav_dropbtn">
                                Equipamento
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mynav_dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Equipamentos" asp-action="Index">Equipamentos</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TipoEquipamentos" asp-action="Index">Tipo de Equipamentos</a>
                            </div>
                        </div>
                        <div class="mynav_dropdown">
                            <button class="mynav_dropbtn">
                                RLF FC
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="mynav_dropdown-content">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Atletas" asp-action="Index">Atletas</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jogos" asp-action="Index">Jogos</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Scouts" asp-action="Index">Scouts</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Scouts" asp-action="Ranking">Ranking</a>
                            </div>
                        </div>*@
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - <a href="https://finance.yahoo.com/">B3 Analytcs</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $body = $("body");

        $(document).on({
            ajaxStart: function () { $body.addClass("loading"); },
        });

        //Initiates an AJAX request on click
        $(document).on("submit", function () {
            $.get("/mockjax");
        });

    </script>
</body>
</html>